kind: Deployment
apiVersion: apps/v1
metadata:
  name: fishnet
  labels:
    app: fishnet
    app.kubernetes.io/component: fishnet
    app.kubernetes.io/instance: fishnet
    app.kubernetes.io/name: fishnet
    app.kubernetes.io/part-of: fishnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fishnet
  template:
    metadata:
      labels:
        app: fishnet
        deployment: fishnet
    spec:
      containers:
        - name: fishnet
          image: docker.io/niklasf/fishnet:2
          envFrom:
            - secretRef:
                name: fishnet
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
